import { Geist, Geist_Mono, Inter } from "next/font/google";
import "@/styles/globals.css";
import Navber from "@/components/layouts/Navber";
import Footer from "@/components/layouts/Footer";

const geistSans = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${inter.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navber/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
