import {
  // General / deliver icons (lucide-react)
  Check,
  Laptop,
  LayoutDashboard,
  Lock,
  Plug,
  CreditCard,
  Search,
  Rocket,
  ShieldCheck,
  Component,
  Smartphone,
  Accessibility,
  Sparkles,
  Palette,
  BookOpen,
  TestTube,
  Database,
  Cloud,
  Mail,
  Upload,
  Activity,
  Shield,
  Layout,
  Server,
  CloudUpload,
  Headphones,
} from "lucide-react";

import {
  // Brand / tech stack icons (react-icons)
  SiReact,
  SiNextdotjs,
  SiTypescript,
  SiNodedotjs,
  SiMongodb,
  SiTailwindcss,
  SiVercel,
  SiExpress,
  SiPostgresql,
  SiRedis,
  SiDocker,
  SiGithubactions,
  SiGithub,
  SiFramer,
  SiRedux,
  SiJest,
  SiFigma,
  SiGsap,
} from "react-icons/si";

import { FaAws } from "react-icons/fa";

// Generic icons (whatIs bullets, deliver cards)
export const iconMap = {
  "ti-check": Check,
  "ti-device-laptop": Laptop,
  "ti-layout-dashboard": LayoutDashboard,
  "ti-lock": Lock,
  "ti-api": Plug,
  "ti-credit-card": CreditCard,
  "ti-search": Search,
  "ti-rocket": Rocket,
  "ti-shield-lock": ShieldCheck,
  "ti-components": Component,
  "ti-device-mobile": Smartphone,
  "ti-accessible": Accessibility,
  "ti-brand-gsap": SiGsap,
  "ti-paint": Palette,
  "ti-brand-storybook": BookOpen,
  "ti-test-pipe": TestTube,
  "ti-database": Database,
  "ti-cloud": Cloud,
  "ti-mail": Mail,
  "ti-file-upload": Upload,
  "ti-activity": Activity,
  "ti-shield": Shield,
  "ti-layout": Layout,
  "ti-server-2": Server,
  "ti-cloud-upload": CloudUpload,
  "ti-headphones": Headphones,
};

// Brand / tech stack icons (Simple Icons via react-icons)
export const techIconMap = {
  "ti-brand-react": SiReact,
  "ti-brand-nextjs": SiNextdotjs,
  "ti-brand-typescript": SiTypescript,
  "ti-brand-nodejs": SiNodedotjs,
  "ti-brand-mongodb": SiMongodb,
  "ti-brand-tailwind": SiTailwindcss,
  "ti-brand-aws": FaAws,
  "ti-brand-vercel": SiVercel,
  "ti-brand-express": SiExpress,
  "ti-brand-postgresql": SiPostgresql,
  "ti-brand-redis": SiRedis,
  "ti-brand-docker": SiDocker,
  "ti-brand-github": SiGithub,
  "ti-brand-github-ci": SiGithubactions,
  "ti-brand-gsap": SiGsap,
  "ti-brand-redux": SiRedux,
  "ti-test-pipe": SiJest,
  "ti-brand-figma": SiFigma,
};
