// Filter bar categories
export const serviceCategories = [
  { id: 0, label: "All Services", value: "all", icon: "ti-layout-grid" },
  {
    id: 1,
    label: "Custom Web Development",
    value: "custom-web",
    icon: "ti-world",
  },
  { id: 2, label: "Frontend Development", value: "frontend", icon: "ti-code" },
  {
    id: 3,
    label: "Backend Development",
    value: "backend",
    icon: "ti-server-2",
  },
  {
    id: 4,
    label: "Full Stack Development",
    value: "fullstack",
    icon: "ti-layers-difference",
  },
  { id: 5, label: "SaaS Development", value: "saas", icon: "ti-cloud" },
  {
    id: 6,
    label: "Dashboard & CRM Systems",
    value: "dashboard-crm",
    icon: "ti-chart-bar",
  },
  {
    id: 7,
    label: "E-Commerce Development",
    value: "ecommerce",
    icon: "ti-shopping-cart",
  },
  { id: 8, label: "UI/UX Design", value: "uiux", icon: "ti-vector-bezier-2" },
  {
    id: 9,
    label: "Website Maintenance",
    value: "maintenance",
    icon: "ti-tool",
  },
  {
    id: 10,
    label: "Technical Support",
    value: "support",
    icon: "ti-headphones",
  },
];

// Service cards data
// layout: "half" = 2-col | "third" = 3-col | "full" = full-width
// Order in this array controls render order in the bento grid.
// Consecutive same-layout items are auto-grouped into rows by ServiceBentoGrid.
export const services = [
  {
    id: 1,
    num: "01",
    popular: true,
    value: "custom-web",
    title: "Custom Web\nDevelopment",
    desc: "High-performance websites tailored to your business goals with modern technologies.",
    tags: [
      "Responsive Design",
      "Fast Performance",
      "SEO Optimized",
      "CMS Integration",
    ],
    icon: "ti-world",
    iconColor: "#ff5101",
    layout: "half",
  },
  {
    id: 2,
    num: "02",
    popular: false,
    value: "frontend",
    title: "Frontend\nDevelopment",
    desc: "Pixel-perfect, responsive and interactive interfaces that deliver exceptional user experiences.",
    tags: ["React", "Next.js", "TypeScript", "Tailwind CSS"],
    icon: "ti-code",
    iconColor: "#8b5cf6",
    layout: "half",
  },
  {
    id: 3,
    num: "03",
    popular: false,
    value: "backend",
    title: "Backend\nDevelopment",
    desc: "Robust, secure and scalable backend systems that power your digital products.",
    tags: ["Node.js", "Express", "REST API", "Database"],
    icon: "ti-server-2",
    iconColor: "#3b82f6",
    layout: "half",
  },
  {
    id: 4,
    num: "04",
    popular: false,
    value: "fullstack",
    title: "Full Stack\nDevelopment",
    desc: "End-to-end development solutions that handle everything from front to backend seamlessly.",
    tags: ["MERN Stack", "Next.js", "API", "Database"],
    icon: "ti-layers-difference",
    iconColor: "#14b8a6",
    layout: "half",
  },
  {
    id: 5,
    num: "05",
    popular: false,
    value: "saas",
    title: "SaaS\nDevelopment",
    desc: "Scalable SaaS platforms with powerful features, secure architecture and seamless UX.",
    tags: ["Multi-tenant", "Subscription", "Billing", "API Integration"],
    icon: "ti-cloud",
    iconColor: "#22c55e",
    layout: "third",
  },
  {
    id: 6,
    num: "06",
    popular: false,
    value: "dashboard-crm",
    title: "Dashboard &\nCRM Systems",
    desc: "Data-driven dashboards and CRM systems to manage your business smarter and faster.",
    tags: ["Analytics", "CRM", "Reports", "Automation"],
    icon: "ti-chart-bar",
    iconColor: "#eab308",
    layout: "third",
  },
  {
    id: 7,
    num: "07",
    popular: false,
    value: "ecommerce",
    title: "E-Commerce\nDevelopment",
    desc: "Conversion-focused online stores with smooth shopping experience and secure payments.",
    tags: ["Shopify", "WooCommerce", "Stripe", "Custom Solutions"],
    icon: "ti-shopping-cart",
    iconColor: "#ec4899",
    layout: "third",
  },
  {
    id: 8,
    num: "08",
    popular: false,
    value: "uiux",
    title: "UI/UX\nDesign",
    desc: "Beautiful, intuitive and user-centered designs that enhance engagement and drive conversions.",
    tags: ["User Research", "Wireframing", "Prototyping", "Design System"],
    icon: "ti-vector-bezier-2",
    iconColor: "#ec4899",
    layout: "half",
  },
  {
    id: 9,
    num: "09",
    popular: false,
    value: "maintenance",
    title: "Website\nMaintenance",
    desc: "We keep your applications fast, secure and up-to-date so you can focus on growing your business.",
    tags: ["Bug Fixing", "Updates", "Monitoring", "24/7 Support"],
    icon: "ti-headphones",
    iconColor: "#06b6d4",
    layout: "half",
  },
  {
    id: 10,
    num: "10",
    popular: false,
    value: "support",
    title: "Technical Support & Maintenance",
    desc: "Round-the-clock technical support to ensure your digital products run flawlessly at every stage of growth.",
    tags: ["Bug Fixing", "Updates", "Monitoring", "24/7 Support"],
    icon: "ti-headphones",
    iconColor: "#ff5101",
    layout: "full",
  },
];
